cafe/urls.py
from django.urls import path
from . import views

app_name = 'cafe'

urlpatterns = [
    # Add cafe page (placed before the cafe home page pattern)
    path('add/', views.AddCafe.as_view(), name='add'),
    
    # Cafe home page
    path('', views.IndexClassView.as_view(), name='index'),
]

cafeandwifi/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cafe/',include('cafe.urls')),
    path('register/',user_views.SignUpView.as_view(),name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='user/logout.html'),name='logout')
]

cafe/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class CafeList(models.Model):

    def __str__(self):
        return self.cafe_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)

    cafe_name = models.CharField(max_length=200)
    cafe_wifi = models.BooleanField(default=False)
    cafe_address = models.CharField(max_length=1000, default='N/A')
    cafe_rating = models.CharField(max_length=5, default='NIL')


    def get_absolute_url(self):
        return reverse("cafe:index")

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100,default='Unknown')

    def __str__(self):
        return self.user.username

cafe/forms.py
from django import forms
from .models import CafeList

class CafeForm(forms.ModelForm):
    class Meta:
        model = CafeList
        fields = ['cafe_name','cafe_wifi','cafe_address','cafe_rating']
        

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField

    class Meta:
        model = User
        fields = ['username', 'email','password1','password2']

cafe/views.py
from django.shortcuts import render
from .models import CafeList
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

# Create your views here.

class IndexClassView(ListView):
    model = CafeList
    template_name = 'cafe/index.html'
    context_object_name = 'cafe_list'

class AddCafe(CreateView):
    model = CafeList;  
    fields = ['cafe_name','cafe_wifi','cafe_address','cafe_rating']
    template_name = 'cafe/add-cafe.html'
    

user/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import RegistrationForm  
from django.views.generic.detail import DetailView
from django.contrib import messages


class SignUpView(CreateView):
    form_class = RegistrationForm  
    template_name = 'user/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('login')
       
   

cafe/templates/cafe/add-cafe.html
{% extends 'cafe/base.html'%}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add New Cafe
                    </div>

                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field.name}}
                                <br>
                                {{field}}

                            </div>
                        {% endfor %}
                        <br>
                        <button type="submit" class="btn btn-primary">Add Cafe</button>
 
                    </form>
                    

                </div>

            </div>

        </div>

    </div>

</div>


{% endblock %}
    

cafe/templates/cafe/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <!-- Link to Bootstrap Css  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <!-- Link to Bootstrap JavaScript  -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    
    <!-- Link to your custom CSS file using the { static } tag -->
    <link rel="stylesheet" href="{% static 'cafe/style.css' %}">
</head>
<body>
    <nav class="navbar  navbar-expand-lg " style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">DEV CENTER</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'cafe:index'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cafe:add' %}">Add Cafe</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout'%}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
              <a class="nav-link" href="{% url 'register'%}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login'%}">Login</a>
            </li>
            {% endif %}
              
            </ul>
          </div>
        </div>
      </nav>
      

      {% block body %}
      {% endblock %}

</body>
</html>

cafe/templates/cafe/index.html
{% extends 'cafe/base.html' %}
{% block body %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Wifi</th>
            <th scope="col">Cafe Address</th>
            <th scope="col">Ratings(⭐⭐⭐⭐⭐)</th>
        </tr>
    </thead>
    {% for cafe in cafe_list %}
    <tbody>
        <tr>
            <th scope="row">{{cafe.id}}</th>
            <td>{{cafe.cafe_name}}</td>
            <td>{{cafe.cafe_wifi}}</td>
            <td>{{cafe.cafe_address}}</td>
            <td>{{cafe.cafe_rating}}</td>

        </tr>
    </tbody>

    {% endfor %}

{% endblock %}

  

user/templates/user/login.html
{% extends 'cafe/base.html'%}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Log in to your account
                    </div>

                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field.name}}
                                <br>
                                {{field}}

                            </div>
                        {% endfor %}
                        <br>
                        <button type="submit" class="btn btn-primary">Log in! </button>
 
                    </form>
                    

                </div>

            </div>

        </div>

    </div>

</div>








{% endblock %}

<

user/templates/user/logout.html
{% extends 'cafe/base.html'%}
{% block body %}

<h1>Your account have been logout</h1>


{% endblock%}

user/templates/user/register.html
{% extends 'cafe/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register a new account
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <br>
                        <button type="submit" class="btn btn-primary">Sign up!</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}